name: "Podchast Generator"
author: "Sandeep Sagar"
description: "Generate Podchast from RSS feed"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "blue"
inputs:
  email:
    description: "the commiter email addres"
    required: true
    default: ${{github.actor}}@localhost
  name:
    description: "the commiter name"
    required: true
    default: ${{github.actor}}